apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatapp-frontend
  template:
    metadata:
      labels:
        app: chatapp-frontend
    spec:
      containers:
        - name: chatapp-frontend
          image: <your-dockerhub-username>/chatapp-frontend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: chatapp-frontend-svc
spec:
  type: LoadBalancer
  selector:
    app: chatapp-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
