apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatapp-backend
  template:
    metadata:
      labels:
        app: chatapp-backend
    spec:
      containers:
        - name: chatapp-backend
          image: <your-dockerhub-username>/chatapp-backend:latest
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: chatapp-config
---
apiVersion: v1
kind: Service
metadata:
  name: chatapp-backend-svc
spec:
  type: ClusterIP
  selector:
    app: chatapp-backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
